config/routes.rb
Rails.application.routes.draw do

  root "index#index"
  match '/catalog/:alias', to: "catalog#item", via: "get"
  match '/other_products/:alias', to: "catalog#other_item", via: "get"
  match '/ajax_call_back_form', to: "index#send_call_back_form", via: "post"
  match '/download_price', to: "index#download_price", via: "get"

  scope "/admin" do
    mount ModulesD::Engine => "/"
    mount SystemMainItemsD::Engine => "/"
    mount SystemUsersAuthorizeD::Engine => "/"
    mount AccessRightsD::Engine => "/"
    mount SystemUserActionsLogD::Engine => "/"
    scope module: "admin" do
      resources :articles
      resources :requests
      resources :categories
      resources :product_types
      resources :products
      resources :news_items
      resources :localizations
    end
  end

end

app/views/index/slides/_arrows.html.slim
.arrows
  .left_arrow
  .right_arrow

app/views/index/slides/_card_1.html.slim
#d3_card.screen style="display: none;"

  .categories
    ul
      li
        = link_to "Категория 1", "#"
      li
        = link_to "Категория 2", "#", class: "active"
      li
        = link_to "Категория 3", "#"
      li
        = link_to "Категория 4", "#"
      li
        = link_to "Категория 5", "#"

  .description
    | Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

  .info
    .cnt
      table
        tr
          td
            | Номинальная мощность, Вт
          td.value
            | 450
        tr
          td
            | Напряжение, В
          td.value
            | 220
        tr
          td
            | Номинальный ток, А
          td.value
            | 2
        tr
          td
            | Компенсирующий момент на валу, Н*м
          td.value
            | 18
        tr
          td
            | Диапазон частотывращения, мин-1
          td.value
            | 1,2 - 420
        tr
          td
            | Габаритные размеры, мм
          td.value
            | 112х112х135*
        tr
          td
            | Масса, кг
          td.value
            | 5,6
        tr
          td colspan=2
            | Тип электродвигателя  - синхронный, переменного тока с постоянными магнитами

app/views/index/slides/_categories.html.slim
#kb_categories.screen
  .labels
    = image_tag "main_right.png", class: "main left_arrow"
    = image_tag "products_kb_right.png", class: "products_gz_right right_arrow"

  .categories
    ul
      - @our_category.each do |category|
        li.category_item
          .category_description
            .top_square
            .title
              = category.name
            .description
              = category.description
          .products
            ul
              - category.products.all.order(:position).each do |product|
                li.product_item
                  .top_square
                  = link_to "/catalog/#{product.alias}"
                    - image = product.preview.url
                    .image style="background-image: url(#{image});"
                    .name
                      = product.name

app/views/index/slides/_contacts.html.slim
#contacts.screen
  .labels
    = image_tag "main_left.png", class: "main_left right_arrow"
  .description
    .first_description
      = Localization.find_by(:alias => "about_us_slide_first_description").value.html_safe
    .second_description
      .text
        = Localization.find_by(:alias => "about_us_slide_second_description").value.html_safe

  ul.news
    - NewsItem.order(:date).each do |news_item|
      li
        span.title
          = news_item.description
        span.delimiter
        span.date
          = news_item.date.strftime("%d.%m.%Y")


  .additional
    | Вы можете
    br
    | получить бесплатную
    br
    | конультацию по продукции
    br
    | и услугам компании, позвонив по телефону,
    br
    | либо просто бесплатно
    span#callback
      | закажите обратный звонок


  .popup#order_popup
    .bg
    .section
      .popup_cnt
        .cnt
          .header
            | Заказать обратный звонок
          = form_tag(ajax_call_back_form_path, :id=>"order_form", :method=>'post', :multipart => true) do
            .text_field
              = text_field_tag "name", nil, :placeholder => "Введите имя"
              .error
                | Поле должно быть заполнено

            .text_field
              = text_field_tag "phone", nil, :placeholder => "Введите телефон"
              .error
                | Поле должно быть заполнено

            .submit
              input class="button blue_button" type="submit" value="Отправить"

        .triumph
          | Ваша заявка успешно отправлена

app/views/index/slides/_footer.html.slim
= image_tag "down-corner.png", class: "left-bottom-corner"


footer
  ul
    li.copyright
      | © 2015 ООО "КБ "Электромаш"
    li.new_screen_pagination
      .pagination
        .paginate_item
        .paginate_item.active
        .paginate_item
    li.mail
      = link_to "", "http://arcsis.ru/", class: "studio_logo", target: "_blank"
      = link_to "info@kb-elektromash.ru", "mailto:info@kb-elektromash.ru", class: "mail"

app/views/index/slides/_header.html.slim
= image_tag "top-corner.png", class: "right-top-corner"

header
  nav
    ul
      li
        .contact
          span.code
            .sota_icon
            = link_to "3412", "tel:+7 (3412) 247-040"
          = link_to "247-040", "tel:+7 (3412) 247-040", class: "phone"
      li
        = link_to "О нас", root_url + "#contacts", class: "animate item about_us_link"
      li
        = link_to root_url + "#main", class: "animate"
          = image_tag "header-logo.png", class: "logo main_link"
      li
        = link_to "Каталог", root_url + "#kb_categories", class: "animate item catalog_link"
      li
        = link_to "Прайс лист", "/download_price", class: "item"

app/views/index/slides/_main.html.slim
#main.screen
  .labels
    = image_tag "about.png", class: "about left_arrow"
    = image_tag "products_gz_right.png", class: "products_gz_right right_arrow"

  .logo_cnt
    = image_tag "large-logo.png"
  .description
    .line
      | ООО «Конструкторское Бюро «Электромаш» разрабатывает электроприводную технику, реализует управление различными механизмами, производит силовую электронику

app/views/index/slides/_other_categories.html.slim
#sgz_categories.screen
  .labels
    = image_tag "products_gz_left.png", class: "products_gz_left left_arrow"

  .categories
    ul
      - @other_category.each do |category|
        li.category_item
          .category_description
            .top_square
            .title
              = category.name
            .description
              = category.description
          .products
            ul
              - category.products.all.order(:position).each do |product|
                li.product_item
                  .top_square
                  = link_to "/catalog/#{product.alias}"
                    - image = product.preview.url
                    .image style="background-image: url(#{image});"
                    .name
                      = product.name